import React from "react";

 export const movies=[
    {
        name: "DAINANDINI: VICHAR PRAVAH (Hindi Edition) ",
        date: "2 Nov, 2022",
        picture: "public/book1.jpeg",
        author: "JYOTINDRA NATH PRASAD",
        webpage: "https://www.amazon.in/gp/product/B0BLD369G7/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i0",
        captionn: "This book has been written in the shape of a diary. The diary was written from the year 2013 to 2017.After relinquishing the office in 2013, the author is trying to adjust with a life of leizure.He is no more bustling with life. After being adept to hurly -burly of life, he has reached a halt in life.He  ",
        caption: "welcome friends",
        end: "300",
    },
    {
        name: "DIARY:SAGA UNTOLD ",
        date: "25 Oct, 2022",
        picture: "/book2.jpeg",
        author: "JYOTINDRA NATH PRASAD",
        webpage: "https://www.amazon.in/gp/product/B0BKKWCJW3/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i1",
        captionn: "This diary book registers my transfer to Chhattisgarh in the fag end of career as reporter. Little surprise that I had to pay for my conscientious rebellion at the ‘Hindustan Times’, which culminated in exit from it. My aggressiveness continued in Chhattisgarh for some time and later I softened to adjust",
    },
    {
        name: "DIARY: ONE STORY MORE  ",
        date: "10 Sep, 2022",
        picture: "/book3.jpeg",
        author: "JYOTINDRA NATH PRASAD",
        webpage: "https://www.amazon.in/gp/product/B0BDXBJM75/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i2",
        captionn: "This diary is fifth in a row being published by Amazon Kindle. It is the last diary chronicling events happening during my reporting at the 'Hindustan Times' in Patna from 2007 to 2012. It was written whenever I resorted to Fatuha, my native place, from hurly-burly of life in the state capital to find ",
    },
    {
        name: "El Dorado  ",
        date: "10 Jul, 2022",
        picture: "/book4.jpeg",
        author: "JYOTINDRA NATH PRASAD",
        webpage: "https://www.amazon.in/gp/product/B0B68YVLGJ/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i3",
        captionn: "It is spiritual book containing 29 articles. It takes you to El Dorado, a land of gold. The book is virtually full of gems and jewelleries. Its one piece strikes upon your identity and surmises that you are 'Shivoham'. All worldly identities have been dismissed and self has been created to say 'Aham  ",
    },
    {
        name: "Dainandini:Ghar-Baahar (Hindi Edition)  ",
        date: "23 May, 2022",
        picture: "/book5.jpeg",
        author: "JYOTINDRA NATH PRASAD",
        webpage: "https://www.amazon.in/gp/product/B0B25S1B33/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i4",
        captionn: "The book is in shape of a diary.It shows daily happenings in the life of a Press Reporter at the Hindustan Times who fearlessly performs his job. He is self-confident and has courage of conviction. He is depressed but shoulders the responsibility of his office and house.During reporting he catches weak",
    },
    {
        name: "Shabdashah (Hindi Edition)  ",
        date: "19 May, 2022",
        picture: "/book6.jpeg",
        author: "JYOTINDRA NATH PRASAD",
        webpage: "https://www.amazon.in/gp/product/B0B1T5S5S8/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i5",
        captionn: "The title of this book 'Shabdshah' means word by word. Letters are 'Brahma(God)' and words are not perished. The words are immortal and every word spoken so far is believed to be echoing in th e universe, So I introduce you with Brahma.It is in literary form,Literature is a penance, in which writers",
    },
    {
        name: "DIARY:GOSSIP SWEET AND SOUR ",
        date: "12 May, 2022 ",
        picture: "/book7.jpeg",
        author: "JYOTINDRA NATH PRASAD",
        webpage: "https://www.amazon.in/gp/product/B0B18B63X7/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i6",
        captionn: "This book is in the form of a diary. It unfolds the lives of certain politicians, officials, journalists, managers, celebrities and women with whom this reporter interacted. He is influenced with them and in turn influences them. The author feels that he came in contact with so small a group",
    },
    {
        name: "DIARY OF A PRESS REPORTER  ",
        date: "19 Mar, 2022",
        picture: "/book8.jpeg",
        author: "JYOTINDRA NATH PRASAD",
        webpage: "https://www.amazon.in/gp/product/B09W1LGWP1/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i7",
        captionn: "Jyotindra Nath Prasad is the author of this book ‘Diary of a Press Reporter’. He is a senior free-lance journalist based in Patna and author of nine books.This new book ‘Diary of a Press Reporter’ as is evident from the title is the day-to-day chronicle of the happenings in the career of ",
    },
    {
        name: "SEARCH WITHIN  ",
        date: "4 Mar, 2022",
        picture: "/book9.jpeg",
        author: "JYOTINDRA NATH PRASAD",
        webpage: "https://www.amazon.in/gp/product/B09TY54M3T/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i8",
        captionn: "I am present with second part of my autobiography entitled ‘Search Within’. The first was ‘Yadon Ke Satrein’. The third volume was entitled ‘My Date with Editors’. While first volume revolved round my childhood to adolescence the third centred on my profession of journalism.The second pa  ",
    },
    {
        name: "UNTO THE BYZANTINE   ",
        date: "25 Feb, 2022",
        picture: "/book10.jpeg",
        author: "JYOTINDRA NATH PRASAD",
        webpage: "https://www.amazon.in/gp/product/B09THJSPZ9/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i9",
        captionn: "The title of the book ‘Unto The Byzantine’ signifies a land of felicity. Symbolically it is a dream land. I have taken the readers to a new place where there is bliss, hope, love, equality and human values.It is a collection of 22 articles on different subjects. My blogs on social media  ",

    },
    {
        name: "Diary:Journey Of The Self   ",
        date: "14 Feb, 2022",
        picture: "/book11.jpeg",
        author: "JYOTINDRA NATH PRASAD",
        webpage: "https://www.amazon.in/gp/product/B09SJ6MD2M/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i10",
        captionn: "This book ‘Diary: Journey Of The Self’ is to the self and through the self. The author bares his soul. The book realms in spiritualism.The author guides to live a spiritual life instead of worldly. Thus, stress is on being human and not beastly.", 
    },
    {
        name: "Yaadon Ke Satrein (Jyotindra Nath Prasad's books Book 5) ",
        date: "30 Aug, 2020",
        picture: "/book12.jpeg",
        author: "JYOTINDRA NATH PRASAD",
        webpage: "https://www.amazon.in/gp/product/B08H3N92YL/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i11",
        captionn: "This book is second part of the author’s autobiography. First part ‘My Date With Editors’ realmed in his journalistic career. Published by the Educreation Publishing as debut book, it received good response from the readers including colleagues, friends, relatives and, of course, editors ",
    },
]

